eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

---
spring.profiles: r1
server:
  port: 8761

eureka:
  instance:
    hostname: service-registry1
  client:
    serviceUrl:
      defaultZone: http://service-registry2:8762/eureka/

---
spring.profiles: r2
server:
  port: 8762

eureka:
  instance:
    hostname: service-registry2
  client:
    serviceUrl:
      defaultZone: http://service-registry1:8761/eureka/